default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username:
  password:

rds_settings: &rds_settings
  database: <%= ENV["RDS_DB_NAME"] %>
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOSTNAME"] %>
  port: <%= ENV["RDS_PORT"] %>

development: &development
  <<: *default
  database: consul_development

test:
  <<: *default
  database: consul_test

production:
  <<: *default
  <<: *rds_settings

staging:
  <<: *default
  <<: *rds_settings

preproduction:
  <<: *default
  <<: *rds_settings
